create table if not exists public.staff_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  role text not null check (role in ('admin', 'manager', 'staff')) default 'staff',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.products (
  id text primary key,
  school text not null default '',
  name text not null,
  sizes jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.products add column if not exists display_order integer;

create table if not exists public.orders (
  id text primary key,
  school text not null default '',
  cashier_id uuid not null references auth.users(id),
  cashier_name text not null default '',
  total integer not null check (total >= 0),
  item_count integer not null check (item_count > 0),
  created_at timestamptz not null default now()
);

alter table public.orders add column if not exists outlet_name text;
alter table public.orders add column if not exists outlet_address text;
alter table public.orders add column if not exists outlet_phone text;

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id text not null references public.orders(id) on delete cascade,
  name text not null,
  size text not null,
  price integer not null check (price >= 0),
  qty integer not null check (qty > 0)
);

alter table public.order_items add column if not exists length text;

create table if not exists public.daily_receipt_sequences (
  receipt_date date primary key,
  last_number integer not null check (last_number >= 0)
);

create or replace function public.current_staff_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select role from public.staff_profiles where id = auth.uid();
$$;

drop function if exists public.create_order_with_items(jsonb);

create function public.create_order_with_items(order_data jsonb)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  current_receipt_date date := (now() at time zone 'Asia/Hong_Kong')::date;
  receipt_number integer;
  receipt_id text;
begin
  if (order_data ->> 'cashier_id')::uuid <> auth.uid() then
    raise exception 'cashier_id must match the signed-in user';
  end if;

  insert into public.daily_receipt_sequences (receipt_date, last_number)
  values (current_receipt_date, 1)
  on conflict (receipt_date) do update set last_number = daily_receipt_sequences.last_number + 1
  returning last_number into receipt_number;
  receipt_id := format('VU-%s-%s', to_char(current_receipt_date, 'YYYYMMDD'), lpad(receipt_number::text, 4, '0'));

  insert into public.orders (id, school, outlet_name, outlet_address, outlet_phone, cashier_id, cashier_name, total, item_count, created_at)
  values (
    receipt_id,
    coalesce(order_data ->> 'school', ''),
    nullif(order_data ->> 'outletName', ''),
    nullif(order_data ->> 'outletAddress', ''),
    nullif(order_data ->> 'outletPhone', ''),
    auth.uid(),
    coalesce(order_data ->> 'cashier_name', ''),
    (order_data ->> 'total')::integer,
    (order_data ->> 'item_count')::integer,
    coalesce((order_data ->> 'created_at')::timestamptz, now())
  );

  insert into public.order_items (order_id, name, size, length, price, qty)
  select receipt_id, item.name, item.size, nullif(item.length, ''), item.price, item.qty
  from jsonb_to_recordset(order_data -> 'items') as item(name text, size text, length text, price integer, qty integer);

  return receipt_id;
end;
$$;

create or replace function public.migrate_legacy_products()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  migrated_count integer;
begin
  if public.current_staff_role() <> 'admin' then
    raise exception 'admin role required';
  end if;

  insert into public.products (id, school, name, sizes)
  select item ->> 'id', coalesce(item ->> 'school', ''), item ->> 'name', coalesce(item -> 'sizes', '[]'::jsonb)
  from public.app_storage storage
  cross join lateral jsonb_array_elements(storage.value::jsonb) item
  where storage.key = 'products'
  on conflict (id) do update set
    school = excluded.school,
    name = excluded.name,
    sizes = excluded.sizes,
    updated_at = now();

  get diagnostics migrated_count = row_count;
  return migrated_count;
end;
$$;

create or replace function public.migrate_legacy_data()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  product_count integer := 0;
  order_count integer := 0;
  legacy_order jsonb;
  legacy_item jsonb;
  inserted boolean;
  legacy_items jsonb;
  legacy_date date;
begin
  if public.current_staff_role() <> 'admin' then
    raise exception 'admin role required';
  end if;

  insert into public.products (id, school, name, sizes)
  select item ->> 'id', coalesce(item ->> 'school', ''), item ->> 'name', coalesce(item -> 'sizes', '[]'::jsonb)
  from public.app_storage storage
  cross join lateral jsonb_array_elements(storage.value::jsonb) item
  where storage.key = 'products'
  on conflict (id) do update set
    school = excluded.school,
    name = excluded.name,
    sizes = excluded.sizes,
    updated_at = now();
  get diagnostics product_count = row_count;

  for legacy_order in
    select item
    from public.app_storage storage
    cross join lateral jsonb_array_elements(storage.value::jsonb) item
    where storage.key = 'sales-log'
  loop
    legacy_items := coalesce(legacy_order -> 'items', '[]'::jsonb);
    legacy_date := coalesce(nullif(legacy_order ->> 'date', '')::date, current_date);

    insert into public.orders (id, school, cashier_id, cashier_name, total, item_count, created_at)
    values (
      legacy_order ->> 'id',
      coalesce(legacy_order ->> 'school', ''),
      auth.uid(),
      coalesce(legacy_order ->> 'cashierName', ''),
      coalesce(nullif(legacy_order ->> 'total', '')::integer, 0),
      coalesce(nullif(legacy_order ->> 'itemCount', '')::integer, jsonb_array_length(legacy_items)),
      legacy_date::timestamptz
    )
    on conflict (id) do nothing;
    inserted := found;

    if inserted then
      for legacy_item in select value from jsonb_array_elements(legacy_items)
      loop
        insert into public.order_items (order_id, name, size, price, qty)
        values (
          legacy_order ->> 'id',
          coalesce(legacy_item ->> 'name', ''),
          coalesce(legacy_item ->> 'size', ''),
          coalesce(nullif(legacy_item ->> 'price', '')::integer, 0),
          coalesce(nullif(legacy_item ->> 'qty', '')::integer, 1)
        );
      end loop;
      order_count := order_count + 1;
    end if;
  end loop;

  return jsonb_build_object('products', product_count, 'orders', order_count);
end;
$$;

alter table public.staff_profiles enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

drop policy if exists "Authenticated staff can read school metadata" on public.app_storage;
create policy "Authenticated staff can read school metadata"
on public.app_storage for select
to authenticated
using (key = 'school-meta');

drop policy if exists "Admins can manage school metadata" on public.app_storage;
create policy "Admins can manage school metadata"
on public.app_storage for all
to authenticated
using (key = 'school-meta' and public.current_staff_role() = 'admin')
with check (key = 'school-meta' and public.current_staff_role() = 'admin');

drop policy if exists "Staff can read own profile" on public.staff_profiles;
create policy "Staff can read own profile"
on public.staff_profiles for select
to authenticated
using (id = auth.uid() or public.current_staff_role() = 'admin');

drop policy if exists "Authenticated staff can read products" on public.products;
create policy "Authenticated staff can read products"
on public.products for select
to authenticated
using (true);

drop policy if exists "Admins can manage products" on public.products;
create policy "Admins can manage products"
on public.products for all
to authenticated
using (public.current_staff_role() = 'admin')
with check (public.current_staff_role() = 'admin');

drop policy if exists "Managers can edit products" on public.products;
create policy "Managers can edit products"
on public.products for update
to authenticated
using (public.current_staff_role() in ('admin', 'manager'))
with check (public.current_staff_role() in ('admin', 'manager'));

drop policy if exists "Authenticated staff can read orders" on public.orders;
create policy "Authenticated staff can read orders"
on public.orders for select
to authenticated
using (public.current_staff_role() in ('admin', 'manager') or cashier_id = auth.uid());

drop policy if exists "Staff can create own orders" on public.orders;
create policy "Staff can create own orders"
on public.orders for insert
to authenticated
with check (cashier_id = auth.uid());

drop policy if exists "Authenticated staff can read order items" on public.order_items;
create policy "Authenticated staff can read order items"
on public.order_items for select
to authenticated
using (exists (
  select 1 from public.orders o
  where o.id = order_items.order_id
    and (public.current_staff_role() in ('admin', 'manager') or o.cashier_id = auth.uid())
));

drop policy if exists "Staff can create order items" on public.order_items;
create policy "Staff can create order items"
on public.order_items for insert
to authenticated
with check (exists (
  select 1 from public.orders o
  where o.id = order_items.order_id and o.cashier_id = auth.uid()
));

grant select on public.staff_profiles, public.products, public.orders, public.order_items to authenticated;
grant insert on public.orders, public.order_items to authenticated;
grant all on public.products to authenticated;
grant usage, select on sequence public.order_items_id_seq to authenticated;
grant select, insert, update on public.daily_receipt_sequences to authenticated;
revoke all on function public.create_order_with_items(jsonb) from public, anon;
grant execute on function public.create_order_with_items(jsonb) to authenticated;
revoke all on function public.migrate_legacy_products() from public, anon;
grant execute on function public.migrate_legacy_products() to authenticated;
revoke all on function public.migrate_legacy_data() from public, anon;
grant execute on function public.migrate_legacy_data() to authenticated;
