alter table public.orders
  add column if not exists voided_at timestamptz,
  add column if not exists voided_by uuid references public.staff_profiles(id),
  add column if not exists void_reason text;

create table if not exists public.order_void_audit (
  id bigint generated by default as identity primary key,
  order_id text not null unique references public.orders(id),
  actor_id uuid not null references public.staff_profiles(id),
  reason text not null check (char_length(btrim(reason)) between 1 and 500),
  created_at timestamptz not null default now()
);

alter table public.order_void_audit enable row level security;

drop policy if exists "Admins can read order void audit" on public.order_void_audit;
create policy "Admins can read order void audit"
on public.order_void_audit
for select
to authenticated
using (public.current_staff_role() = 'admin');

revoke all on public.order_void_audit from anon, authenticated;
grant select on public.order_void_audit to authenticated;

create or replace function public.void_sales_order(p_order_id text, p_reason text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  actor_id uuid := auth.uid();
  void_time timestamptz;
  normalized_reason text := btrim(coalesce(p_reason, ''));
begin
  if actor_id is null or public.current_staff_role() is distinct from 'admin' then
    raise exception 'Admin role required';
  end if;

  if not exists (
    select 1
    from jsonb_array_elements(coalesce(auth.jwt() -> 'amr', '[]'::jsonb)) as auth_methods(method_entry)
    where method_entry ->> 'method' = 'password'
      and (method_entry ->> 'timestamp') ~ '^[0-9]+$'
      and (method_entry ->> 'timestamp')::bigint >= extract(epoch from now())::bigint - 300
  ) then
    raise exception 'Recent admin password verification required';
  end if;

  if nullif(btrim(p_order_id), '') is null then
    raise exception 'Receipt number is required';
  end if;

  if char_length(normalized_reason) not between 1 and 500 then
    raise exception 'A void reason between 1 and 500 characters is required';
  end if;

  if exists (
    select 1
    from public.orders related_order
    where related_order.exchange_source_receipt_id = p_order_id
      and related_order.voided_at is null
  ) then
    raise exception 'Void the related exchange receipt first';
  end if;

  update public.orders
  set voided_at = now(),
      voided_by = actor_id,
      void_reason = normalized_reason
  where id = p_order_id
    and voided_at is null
  returning voided_at into void_time;

  if void_time is null then
    raise exception 'Receipt not found or already voided';
  end if;

  insert into public.order_void_audit (order_id, actor_id, reason, created_at)
  values (p_order_id, actor_id, normalized_reason, void_time);

  return jsonb_build_object('order_id', p_order_id, 'voided_at', void_time);
end;
$$;

revoke all on function public.void_sales_order(text, text) from public, anon;
grant execute on function public.void_sales_order(text, text) to authenticated;
